FROM nvcr.io/nvidia/l4t-ml:r35.2.1-py3
ARG DEBIAN_FRONTEND=noninteractive
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y \
    pkg-config \
    libdbus-1-dev \
    libasound2-dev \
    libavcodec-dev=7:4.2.7-0ubuntu0.1

# Remove conflicting packages
RUN apt-get remove -y opencv-libs opencv-dev

# Install libopencv and libopencv-dev
#RUN pip uninstall opencv-python 4.5.0
#RUN apt-get install -y python-opencv libopencv libopencv-dev
# Remove conflicting package
RUN apt-get remove -y python-opencv opencv-python

# Install libopencv and libopencv-dev
RUN apt-get install -y libopencv libopencv-dev libopencv-python

RUN pip3 install simpleaudio tqdm
RUN pip3 install --upgrade pip
RUN apt-get update --fix-missing && apt -y --no-install-recommends install \
    git \
    cmake \
    autoconf \
    automake \
    libtool \
    libgirepository1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libcairo2-dev \
    gir1.2-gstreamer-1.0 \
    python-gi-dev \
    python3-gi \
    python3-setuptools \
    ffmpeg \
    python3-gi-cairo
RUN apt-get clean && \
        rm -rf /var/lib/apt/lists/*
RUN pip3 install -U pip -v
RUN pip3 --no-cache-dir install -U -v jupyter grpcio absl-py py-cpuinfo psutil portpicker six mock requests gast h5py astor termcolor protobuf keras keras-applications keras-preprocessing wrapt google-pasta
#RUN apt-get update --fix-missing && apt install build-essential autoconf libtool python-opengl python-pil python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev -y
RUN apt install libjpeg-dev zlib1g-dev -y
RUN apt-get update --fix-missing && apt install build-essential libdbus-glib-1-dev -y
RUN apt-get update --fix-missing && apt install redis libicu-dev python3-distutils-extra libudev-dev libsystemd-dev libxml2-dev libcups2-dev libxmlsec1-dev libavformat-dev libavdevice-dev -y
COPY . .
RUN apt-get update --fix-missing && \
    apt-get install -y locales && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8
RUN apt-get update --fix-missing && apt-get install -y python3-gi
RUN apt-get -y install python3-seaborn
RUN pip3 install tqdm psutil
RUN apt-get update --fix-missing && apt -y --no-install-recommends install \
    libjpeg-dev \
    zlib1g-dev \
    libpython3-dev \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev
#RUN python3 -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
RUN apt-get update --fix-missing && \
    apt-get install -y build-essential git

# Clone and build OpenBLAS with OpenMP support
RUN git clone https://github.com/xianyi/OpenBLAS.git && \
    cd OpenBLAS && \
    make USE_OPENMP=1 && \
    make PREFIX=/usr/local install && \
    echo "/usr/local/lib" >> /etc/ld.so.conf.d/openblas.conf && \
    ldconfig
RUN apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
RUN pip3 install -U pillow gdown
RUN gdown https://drive.google.com/uc?id=1BdvXkwUGGTTamM17Io4kkjIT6zgvf4BJ
# Install any other required packages
RUN pip3 install --no-cache-dir \
        pillow
# Clean up build dependencies and source code
RUN apt-get remove -y build-essential git && \
    apt-get autoremove -y && \
    rm -rf /OpenBLAS
RUN apt-get -y install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev

# Update the system and install dependencies
RUN apt-get update --fix-missing && apt-get upgrade -y && \
    apt-get install -y \
    build-essential \
    cmake \
    git \
    libgtk2.0-dev \
    pkg-config \
    libavcodec-dev \
    libavformat-dev \
    libswscale-dev \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff-dev \
    libv4l-dev \
    v4l-utils \
    qv4l2 \
    curl \
    python3-dev \
    python3-testresources \
    python3-tk \
    ffmpeg
# Install necessary packages
#RUN apt-get update && apt-get install -y \
#    alsa-utils \
#    pulseaudio \
#    ffmpeg \
#    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip3 install --upgrade pip setuptools wheel
RUN pip3 install -U setuptools pip wheel
RUN pip3 install --no-cache-dir PyYAML
RUN pip3 install pulsectl

# Install the packages listed in requirements.txt
#RUN pip3 install --no-cache-dir -r requirements.txt

# Install OpenCV using pip with the --no-binary option
RUN pip3 install --no-cache-dir -r requirements.txt
# Install ALSA packages
#RUN apt-get update && apt-get install -y alsa-base

# Install dependencies
RUN apt-get update && apt-get install -y pulseaudio alsa-utils

# Set the default audio sink in the pulseaudio config
RUN echo "default-sample-format = s16le" >> /etc/pulse/daemon.conf
RUN echo "default-sample-rate = 24000" >> /etc/pulse/daemon.conf
RUN echo "default-sample-channels = 2" >> /etc/pulse/daemon.conf

# Install Python and pip
RUN apt-get install -y python3 python3-pip

# Install Python dependencies
RUN pip3 install pulsectl

#ENV AUDIO_BACKEND=alsa
##ENV PULSE_SERVER=host.docker.internal
#RUN pip3 uninstall -y opencv-python && pip3 install opencv-python==4.5.5.64
ENV DISPLAY=:0
RUN apt-get update --fix-missing && apt-get upgrade -y libcanberra-gtk*
EXPOSE 8888 6006
#ENV DISPLAY=:0
CMD pulseaudio --start && python3 anomaly_trigger.py